services:
  linkace-sentry:
    build:
      context: .
      dockerfile: Dockerfile
    image: wajdiab/linkace-sentry:0.0.2
    container_name: linkace-sentry
    volumes:
      - ./src:/app/src
      - ${AWS_CREDENTIALS_PATH:-/home/wajdi/.aws/credentials}:/home/appuser/.aws/credentials:ro
    user: "1000:1000"
    env_file:
      - .env
    environment:
      AWS_REGION: ${AWS_REGION}
      AWS_SNS_TOPIC_ARN: ${AWS_SNS_TOPIC_ARN}

    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
