version: '3.8'

services:
  linkace-sentry:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - LINKACE_API_URL=http://linkace:8080/api
      - LINKACE_API_KEY=your_api_key_here
    volumes:
      - ./src:/app/src
    ports:
      - "8000:8000"
    restart: unless-stopped